#!/usr/bin/env python3
import json

# Read existing data
with open('data.json', 'r') as f:
    data = json.load(f)

# Cities from existing data
cities_data = {
    "Bangkok": {"country": "Thailand", "region": "Southeast Asia", "lat": 13.7563, "lng": 100.5018},
    "Seoul": {"country": "South Korea", "region": "East Asia", "lat": 37.5665, "lng": 126.978},
    "Istanbul": {"country": "Turkey", "region": "Europe / ME", "lat": 41.0082, "lng": 28.9784},
    "Ho Chi Minh City": {"country": "Vietnam", "region": "Southeast Asia", "lat": 10.8231, "lng": 106.6297},
    "Kuala Lumpur": {"country": "Malaysia", "region": "Southeast Asia", "lat": 3.139, "lng": 101.6869},
    "Delhi": {"country": "India", "region": "South Asia", "lat": 28.7041, "lng": 77.1025},
    "Mumbai": {"country": "India", "region": "South Asia", "lat": 19.076, "lng": 72.8777},
    "Mexico City": {"country": "Mexico", "region": "Latin America", "lat": 19.4326, "lng": -99.1332},
    "Medellín": {"country": "Colombia", "region": "Latin America", "lat": 6.2442, "lng": -75.5812},
    "Bogotá": {"country": "Colombia", "region": "Latin America", "lat": 4.711, "lng": -74.0721},
    "Prague": {"country": "Czech Rep.", "region": "Europe", "lat": 50.0755, "lng": 14.4378},
    "Budapest": {"country": "Hungary", "region": "Europe", "lat": 47.4979, "lng": 19.0402},
    "Warsaw": {"country": "Poland", "region": "Europe", "lat": 52.2297, "lng": 21.0122},
    "Dubai": {"country": "UAE", "region": "Middle East", "lat": 25.2048, "lng": 55.2708},
    "Tokyo": {"country": "Japan", "region": "East Asia", "lat": 35.6895, "lng": 139.6917},
    "Barcelona": {"country": "Spain", "region": "Europe", "lat": 41.3851, "lng": 2.1734},
    "London": {"country": "UK", "region": "Europe", "lat": 51.5074, "lng": -0.1278},
    "Paris": {"country": "France", "region": "Europe", "lat": 48.8566, "lng": 2.3522},
    "Los Angeles": {"country": "USA", "region": "North America", "lat": 34.0522, "lng": -118.2437},
    "New York City": {"country": "USA", "region": "North America", "lat": 40.7128, "lng": -74.006},
}

# New procedures with pricing data based on research
new_procedures = [
    {
        "procedure": "Liposuction",
        "category": "Cosmetic",
        "pricing": {
            "Bangkok": {"low": 3500, "high": 6500, "mid": 5000, "currency": "THB", "included": "Surgeon, anesthesia, facility", "notes": "Post-op care", "confidence": "High", "source": "Clinic sites + aggregators", "caveats": "40-60% cheaper than US"},
            "Seoul": {"low": 4000, "high": 8000, "mid": 6000, "currency": "KRW", "included": "Surgeon, VASER tech, facility", "notes": "Advanced imaging", "confidence": "High", "source": "Clinic sites", "caveats": "30-60% savings vs US"},
            "Istanbul": {"low": 1500, "high": 3500, "mid": 2500, "currency": "TRY", "included": "All-inclusive package", "notes": "Hotel, transfers", "confidence": "High", "source": "Aggregators", "caveats": "50-70% savings"},
            "Ho Chi Minh City": {"low": 3000, "high": 5500, "mid": 4200, "currency": "VND", "included": "Surgeon, facility", "notes": "Compression garments", "confidence": "Medium", "source": "Local clinics", "caveats": "Growing market"},
            "Kuala Lumpur": {"low": 3200, "high": 5800, "mid": 4500, "currency": "MYR", "included": "Surgeon, facility", "notes": "Follow-up visits", "confidence": "Medium", "source": "Clinic sites", "caveats": "Mid-range pricing"},
            "Delhi": {"low": 2500, "high": 4500, "mid": 3500, "currency": "INR", "included": "Surgeon, hospital", "notes": "Medications", "confidence": "Medium", "source": "Aggregators", "caveats": "Very affordable"},
            "Mumbai": {"low": 2800, "high": 4800, "mid": 3800, "currency": "INR", "included": "Surgeon, facility", "notes": "Post-op care", "confidence": "Medium", "source": "Clinics", "caveats": "Similar to Delhi"},
            "Mexico City": {"low": 3000, "high": 5600, "mid": 4300, "currency": "MXN", "included": "Surgeon, facility", "notes": "Compression garments", "confidence": "High", "source": "Clinic sites", "caveats": "50-70% cheaper than US"},
            "Medellín": {"low": 2800, "high": 5200, "mid": 4000, "currency": "COP", "included": "Surgeon, hospital", "notes": "Recovery suite", "confidence": "Medium", "source": "Aggregators", "caveats": "Medical tourism hub"},
            "Bogotá": {"low": 3000, "high": 5400, "mid": 4200, "currency": "COP", "included": "Surgeon, facility", "notes": "Follow-up care", "confidence": "Medium", "source": "Clinics", "caveats": "Similar to Medellín"},
            "Prague": {"low": 3500, "high": 6500, "mid": 5000, "currency": "CZK", "included": "Surgeon, facility", "notes": "EU standards", "confidence": "Medium", "source": "Clinic sites", "caveats": "EU pricing"},
            "Budapest": {"low": 3200, "high": 6000, "mid": 4600, "currency": "HUF", "included": "Surgeon, facility", "notes": "All-inclusive", "confidence": "Medium", "source": "Aggregators", "caveats": "Value EU option"},
            "Warsaw": {"low": 3400, "high": 6200, "mid": 4800, "currency": "PLN", "included": "Surgeon, facility", "notes": "Post-op visits", "confidence": "Medium", "source": "Clinics", "caveats": "Growing market"},
            "Dubai": {"low": 5000, "high": 9000, "mid": 7000, "currency": "AED", "included": "Premium surgeon, luxury facility", "notes": "VIP care", "confidence": "High", "source": "Clinic sites", "caveats": "Luxury pricing"},
            "Tokyo": {"low": 4500, "high": 8500, "mid": 6500, "currency": "JPY", "included": "Surgeon, clinic", "notes": "Advanced tech", "confidence": "Medium", "source": "Clinics", "caveats": "High quality care"},
            "Barcelona": {"low": 4000, "high": 7500, "mid": 5750, "currency": "EUR", "included": "Surgeon, facility", "notes": "EU standards", "confidence": "Medium", "source": "Clinics", "caveats": "EU pricing"},
            "London": {"low": 5500, "high": 10000, "mid": 7750, "currency": "GBP", "included": "Surgeon, private clinic", "notes": "Premium care", "confidence": "High", "source": "Clinics", "caveats": "Very expensive"},
            "Paris": {"low": 5000, "high": 9500, "mid": 7250, "currency": "EUR", "included": "Surgeon, facility", "notes": "Premium EU", "confidence": "High", "source": "Clinics", "caveats": "High costs"},
            "Los Angeles": {"low": 7000, "high": 14000, "mid": 10500, "currency": "USD", "included": "Surgeon, facility", "notes": "Premium care", "confidence": "High", "source": "US clinics", "caveats": "Celebrity market"},
            "New York City": {"low": 7500, "high": 15000, "mid": 11250, "currency": "USD", "included": "Surgeon, facility", "notes": "Top surgeons", "confidence": "High", "source": "US clinics", "caveats": "Highest US costs"},
        }
    },
    {
        "procedure": "Tummy Tuck",
        "category": "Cosmetic",
        "pricing": {
            "Bangkok": {"low": 4000, "high": 7000, "mid": 5500, "currency": "THB", "included": "Surgeon, anesthesia, hospital", "notes": "Recovery suite", "confidence": "High", "source": "Clinic sites", "caveats": "International hospitals"},
            "Seoul": {"low": 5000, "high": 9000, "mid": 7000, "currency": "KRW", "included": "Surgeon, facility", "notes": "Advanced techniques", "confidence": "High", "source": "Clinics", "caveats": "Premium quality"},
            "Istanbul": {"low": 3000, "high": 5000, "mid": 3900, "currency": "TRY", "included": "All-inclusive package", "notes": "Hotel, transfers", "confidence": "High", "source": "Aggregators", "caveats": "50-70% savings"},
            "Ho Chi Minh City": {"low": 3500, "high": 6000, "mid": 4750, "currency": "VND", "included": "Surgeon, hospital", "notes": "Post-op care", "confidence": "Medium", "source": "Local clinics", "caveats": "Variable quality"},
            "Kuala Lumpur": {"low": 4000, "high": 6800, "mid": 5400, "currency": "MYR", "included": "Surgeon, facility", "notes": "Medications", "confidence": "Medium", "source": "Clinic sites", "caveats": "Mid-range"},
            "Delhi": {"low": 2000, "high": 4500, "mid": 3250, "currency": "INR", "included": "Surgeon, hospital", "notes": "Post-op care", "confidence": "Medium", "source": "Aggregators", "caveats": "Very affordable"},
            "Mumbai": {"low": 2500, "high": 4500, "mid": 3500, "currency": "INR", "included": "Surgeon, facility", "notes": "Follow-up visits", "confidence": "Medium", "source": "Clinics", "caveats": "Competitive pricing"},
            "Mexico City": {"low": 3000, "high": 6000, "mid": 4500, "currency": "MXN", "included": "Surgeon, facility", "notes": "Compression garments", "confidence": "High", "source": "Clinic sites", "caveats": "Popular with US patients"},
            "Medellín": {"low": 3200, "high": 5800, "mid": 4500, "currency": "COP", "included": "Surgeon, hospital", "notes": "Recovery care", "confidence": "Medium", "source": "Aggregators", "caveats": "Cosmetic hub"},
            "Bogotá": {"low": 3400, "high": 6000, "mid": 4700, "currency": "COP", "included": "Surgeon, facility", "notes": "Post-op care", "confidence": "Medium", "source": "Clinics", "caveats": "Similar to Medellín"},
            "Prague": {"low": 4500, "high": 7500, "mid": 6000, "currency": "CZK", "included": "Surgeon, facility", "notes": "EU standards", "confidence": "Medium", "source": "Clinic sites", "caveats": "EU pricing"},
            "Budapest": {"low": 4000, "high": 7000, "mid": 5500, "currency": "HUF", "included": "Surgeon, facility", "notes": "Comprehensive care", "confidence": "Medium", "source": "Aggregators", "caveats": "Value EU"},
            "Warsaw": {"low": 4200, "high": 7200, "mid": 5700, "currency": "PLN", "included": "Surgeon, facility", "notes": "Post-op visits", "confidence": "Medium", "source": "Clinics", "caveats": "Expanding market"},
            "Dubai": {"low": 6000, "high": 11000, "mid": 8500, "currency": "AED", "included": "Premium surgeon, luxury facility", "notes": "VIP care", "confidence": "High", "source": "Clinic sites", "caveats": "Premium pricing"},
            "Tokyo": {"low": 5500, "high": 10000, "mid": 7750, "currency": "JPY", "included": "Surgeon, clinic", "notes": "High standards", "confidence": "Medium", "source": "Clinics", "caveats": "Conservative approach"},
            "Barcelona": {"low": 5000, "high": 8500, "mid": 6750, "currency": "EUR", "included": "Surgeon, facility", "notes": "EU standards", "confidence": "Medium", "source": "Clinics", "caveats": "EU pricing"},
            "London": {"low": 6500, "high": 12000, "mid": 9250, "currency": "GBP", "included": "Surgeon, private clinic", "notes": "Premium care", "confidence": "High", "source": "Clinics", "caveats": "Very high costs"},
            "Paris": {"low": 6000, "high": 11500, "mid": 8750, "currency": "EUR", "included": "Surgeon, facility", "notes": "Premium EU", "confidence": "High", "source": "Clinics", "caveats": "Premium pricing"},
            "Los Angeles": {"low": 8000, "high": 15000, "mid": 11500, "currency": "USD", "included": "Surgeon, facility", "notes": "Top surgeons", "confidence": "High", "source": "US clinics", "caveats": "Celebrity market"},
            "New York City": {"low": 8500, "high": 16000, "mid": 12250, "currency": "USD", "included": "Surgeon, facility", "notes": "Premium care", "confidence": "High", "source": "US clinics", "caveats": "Highest US costs"},
        }
    },
    {
        "procedure": "Brazilian Butt Lift (BBL)",
        "category": "Cosmetic",
        "pricing": {
            "Bangkok": {"low": 3500, "high": 7000, "mid": 5250, "currency": "THB", "included": "Surgeon, fat transfer, facility", "notes": "Compression garments", "confidence": "High", "source": "Clinic sites", "caveats": "Quality care affordable"},
            "Seoul": {"low": 4500, "high": 8500, "mid": 6500, "currency": "KRW", "included": "Surgeon, facility", "notes": "Advanced techniques", "confidence": "High", "source": "Clinics", "caveats": "Premium cosmetic market"},
            "Istanbul": {"low": 2000, "high": 4000, "mid": 3000, "currency": "TRY", "included": "All-inclusive package", "notes": "Hotel, transfers", "confidence": "High", "source": "Aggregators", "caveats": "Very competitive"},
            "Ho Chi Minh City": {"low": 3200, "high": 6000, "mid": 4600, "currency": "VND", "included": "Surgeon, hospital", "notes": "Post-op care", "confidence": "Medium", "source": "Local clinics", "caveats": "Growing market"},
            "Kuala Lumpur": {"low": 3500, "high": 6500, "mid": 5000, "currency": "MYR", "included": "Surgeon, facility", "notes": "Follow-up care", "confidence": "Medium", "source": "Clinic sites", "caveats": "Mid-range pricing"},
            "Delhi": {"low": 2800, "high": 5000, "mid": 3900, "currency": "INR", "included": "Surgeon, hospital", "notes": "Medications", "confidence": "Medium", "source": "Aggregators", "caveats": "Affordable option"},
            "Mumbai": {"low": 3000, "high": 5200, "mid": 4100, "currency": "INR", "included": "Surgeon, facility", "notes": "Post-op care", "confidence": "Medium", "source": "Clinics", "caveats": "Competitive pricing"},
            "Mexico City": {"low": 3000, "high": 5000, "mid": 4000, "currency": "MXN", "included": "Surgeon, facility", "notes": "Recovery care", "confidence": "High", "source": "Clinic sites", "caveats": "Popular destination"},
            "Medellín": {"low": 3500, "high": 6000, "mid": 4750, "currency": "COP", "included": "Surgeon, hospital", "notes": "Premium care", "confidence": "High", "source": "Aggregators", "caveats": "BBL capital"},
            "Bogotá": {"low": 3700, "high": 6200, "mid": 4950, "currency": "COP", "included": "Surgeon, facility", "notes": "Post-op care", "confidence": "High", "source": "Clinics", "caveats": "Similar to Medellín"},
            "Prague": {"low": 4000, "high": 7000, "mid": 5500, "currency": "CZK", "included": "Surgeon, facility", "notes": "EU standards", "confidence": "Medium", "source": "Clinic sites", "caveats": "EU pricing"},
            "Budapest": {"low": 3800, "high": 6500, "mid": 5150, "currency": "HUF", "included": "Surgeon, facility", "notes": "Comprehensive care", "confidence": "Medium", "source": "Aggregators", "caveats": "Value EU"},
            "Warsaw": {"low": 3900, "high": 6800, "mid": 5350, "currency": "PLN", "included": "Surgeon, facility", "notes": "Post-op visits", "confidence": "Medium", "source": "Clinics", "caveats": "Growing market"},
            "Dubai": {"low": 5500, "high": 10000, "mid": 7750, "currency": "AED", "included": "Premium surgeon, luxury facility", "notes": "VIP care", "confidence": "High", "source": "Clinic sites", "caveats": "Luxury market"},
            "Tokyo": {"low": 5000, "high": 9500, "mid": 7250, "currency": "JPY", "included": "Surgeon, clinic", "notes": "High standards", "confidence": "Medium", "source": "Clinics", "caveats": "Conservative aesthetic"},
            "Barcelona": {"low": 4500, "high": 8000, "mid": 6250, "currency": "EUR", "included": "Surgeon, facility", "notes": "EU standards", "confidence": "Medium", "source": "Clinics", "caveats": "EU pricing"},
            "London": {"low": 6000, "high": 11000, "mid": 8500, "currency": "GBP", "included": "Surgeon, private clinic", "notes": "Premium care", "confidence": "High", "source": "Clinics", "caveats": "Very expensive"},
            "Paris": {"low": 5500, "high": 10500, "mid": 8000, "currency": "EUR", "included": "Surgeon, facility", "notes": "Premium EU", "confidence": "High", "source": "Clinics", "caveats": "High costs"},
            "Los Angeles": {"low": 7500, "high": 14000, "mid": 10750, "currency": "USD", "included": "Surgeon, facility", "notes": "Celebrity surgeons", "confidence": "High", "source": "US clinics", "caveats": "Premium market"},
            "New York City": {"low": 8000, "high": 15000, "mid": 11500, "currency": "USD", "included": "Surgeon, facility", "notes": "Top surgeons", "confidence": "High", "source": "US clinics", "caveats": "Highest US costs"},
        }
    },
    {
        "procedure": "Facelift",
        "category": "Cosmetic",
        "pricing": {
            "Bangkok": {"low": 4500, "high": 8000, "mid": 6250, "currency": "THB", "included": "Surgeon, anesthesia, hospital", "notes": "Recovery care", "confidence": "High", "source": "Clinic sites", "caveats": "High quality affordable"},
            "Seoul": {"low": 6000, "high": 12000, "mid": 9000, "currency": "KRW", "included": "Surgeon, advanced tech", "notes": "Minimal scarring", "confidence": "High", "source": "Clinics", "caveats": "Global leader"},
            "Istanbul": {"low": 3500, "high": 6500, "mid": 5000, "currency": "TRY", "included": "All-inclusive package", "notes": "Hotel, transfers", "confidence": "High", "source": "Aggregators", "caveats": "Very competitive"},
            "Ho Chi Minh City": {"low": 4000, "high": 7000, "mid": 5500, "currency": "VND", "included": "Surgeon, hospital", "notes": "Post-op care", "confidence": "Medium", "source": "Local clinics", "caveats": "Variable quality"},
            "Kuala Lumpur": {"low": 4500, "high": 7500, "mid": 6000, "currency": "MYR", "included": "Surgeon, facility", "notes": "Follow-up visits", "confidence": "Medium", "source": "Clinic sites", "caveats": "Mid-range"},
            "Delhi": {"low": 3000, "high": 5500, "mid": 4250, "currency": "INR", "included": "Surgeon, hospital", "notes": "Medications", "confidence": "Medium", "source": "Aggregators", "caveats": "Affordable"},
            "Mumbai": {"low": 3500, "high": 6000, "mid": 4750, "currency": "INR", "included": "Surgeon, facility", "notes": "Post-op care", "confidence": "Medium", "source": "Clinics", "caveats": "Quality varies"},
            "Mexico City": {"low": 4000, "high": 7500, "mid": 5750, "currency": "MXN", "included": "Surgeon, facility", "notes": "Recovery suite", "confidence": "High", "source": "Clinic sites", "caveats": "Popular with US"},
            "Medellín": {"low": 4200, "high": 7200, "mid": 5700, "currency": "COP", "included": "Surgeon, hospital", "notes": "Premium care", "confidence": "Medium", "source": "Aggregators", "caveats": "Cosmetic hub"},
            "Bogotá": {"low": 4400, "high": 7400, "mid": 5900, "currency": "COP", "included": "Surgeon, facility", "notes": "Post-op care", "confidence": "Medium", "source": "Clinics", "caveats": "Similar to Medellín"},
            "Prague": {"low": 5000, "high": 9000, "mid": 7000, "currency": "CZK", "included": "Surgeon, facility", "notes": "EU standards", "confidence": "Medium", "source": "Clinic sites", "caveats": "EU pricing"},
            "Budapest": {"low": 4500, "high": 8500, "mid": 6500, "currency": "HUF", "included": "Surgeon, facility", "notes": "Comprehensive care", "confidence": "Medium", "source": "Aggregators", "caveats": "Value EU"},
            "Warsaw": {"low": 4800, "high": 8800, "mid": 6800, "currency": "PLN", "included": "Surgeon, facility", "notes": "Post-op visits", "confidence": "Medium", "source": "Clinics", "caveats": "Growing market"},
            "Dubai": {"low": 7000, "high": 13000, "mid": 10000, "currency": "AED", "included": "Premium surgeon, luxury facility", "notes": "VIP care", "confidence": "High", "source": "Clinic sites", "caveats": "Luxury pricing"},
            "Tokyo": {"low": 6500, "high": 12000, "mid": 9250, "currency": "JPY", "included": "Surgeon, clinic", "notes": "Precision techniques", "confidence": "Medium", "source": "Clinics", "caveats": "High quality"},
            "Barcelona": {"low": 5500, "high": 10000, "mid": 7750, "currency": "EUR", "included": "Surgeon, facility", "notes": "EU standards", "confidence": "Medium", "source": "Clinics", "caveats": "EU pricing"},
            "London": {"low": 8000, "high": 15000, "mid": 11500, "currency": "GBP", "included": "Surgeon, private clinic", "notes": "Premium care", "confidence": "High", "source": "Clinics", "caveats": "Very expensive"},
            "Paris": {"low": 7500, "high": 14000, "mid": 10750, "currency": "EUR", "included": "Surgeon, facility", "notes": "Premium EU", "confidence": "High", "source": "Clinics", "caveats": "High costs"},
            "Los Angeles": {"low": 10000, "high": 18000, "mid": 14000, "currency": "USD", "included": "Surgeon, facility", "notes": "Celebrity surgeons", "confidence": "High", "source": "US clinics", "caveats": "Premium market"},
            "New York City": {"low": 11000, "high": 20000, "mid": 15500, "currency": "USD", "included": "Surgeon, facility", "notes": "Top surgeons", "confidence": "High", "source": "US clinics", "caveats": "Highest US costs"},
        }
    },
    {
        "procedure": "IVF (Fertility Treatment)",
        "category": "Fertility",
        "pricing": {
            "Bangkok": {"low": 5000, "high": 10000, "mid": 7500, "currency": "THB", "included": "Full IVF cycle, medications", "notes": "Success rate 40-60%", "confidence": "High", "source": "Clinic sites", "caveats": "50-70% cheaper than US"},
            "Seoul": {"low": 5500, "high": 11000, "mid": 8250, "currency": "KRW", "included": "IVF cycle, advanced tech", "notes": "High success rates", "confidence": "High", "source": "Clinics", "caveats": "Advanced technology"},
            "Istanbul": {"low": 3500, "high": 7000, "mid": 5250, "currency": "TRY", "included": "IVF cycle, medications", "notes": "Hotel packages", "confidence": "High", "source": "Aggregators", "caveats": "Competitive pricing"},
            "Ho Chi Minh City": {"low": 4000, "high": 8000, "mid": 6000, "currency": "VND", "included": "IVF cycle", "notes": "Basic medications", "confidence": "Medium", "source": "Local clinics", "caveats": "Growing market"},
            "Kuala Lumpur": {"low": 4500, "high": 8500, "mid": 6500, "currency": "MYR", "included": "IVF cycle, medications", "notes": "Follow-up care", "confidence": "Medium", "source": "Clinic sites", "caveats": "Mid-range quality"},
            "Delhi": {"low": 2000, "high": 4000, "mid": 3000, "currency": "INR", "included": "IVF cycle", "notes": "Basic care", "confidence": "Medium", "source": "Aggregators", "caveats": "Most affordable"},
            "Mumbai": {"low": 2500, "high": 4500, "mid": 3500, "currency": "INR", "included": "IVF cycle, medications", "notes": "Modern facilities", "confidence": "Medium", "source": "Clinics", "caveats": "Very affordable"},
            "Mexico City": {"low": 4000, "high": 8000, "mid": 6000, "currency": "MXN", "included": "IVF cycle, medications", "notes": "Comprehensive care", "confidence": "High", "source": "Clinic sites", "caveats": "Popular with US"},
            "Medellín": {"low": 3800, "high": 7500, "mid": 5650, "currency": "COP", "included": "IVF cycle", "notes": "Modern clinics", "confidence": "Medium", "source": "Aggregators", "caveats": "Good quality care"},
            "Bogotá": {"low": 4000, "high": 7800, "mid": 5900, "currency": "COP", "included": "IVF cycle, medications", "notes": "Quality facilities", "confidence": "Medium", "source": "Clinics", "caveats": "Similar to Medellín"},
            "Prague": {"low": 5000, "high": 9000, "mid": 7000, "currency": "CZK", "included": "IVF cycle, medications", "notes": "EU standards", "confidence": "Medium", "source": "Clinic sites", "caveats": "EU pricing"},
            "Budapest": {"low": 4500, "high": 8500, "mid": 6500, "currency": "HUF", "included": "IVF cycle", "notes": "Comprehensive care", "confidence": "Medium", "source": "Aggregators", "caveats": "Value EU"},
            "Warsaw": {"low": 4800, "high": 8800, "mid": 6800, "currency": "PLN", "included": "IVF cycle, medications", "notes": "Modern facilities", "confidence": "Medium", "source": "Clinics", "caveats": "Growing market"},
            "Dubai": {"low": 4000, "high": 8000, "mid": 6000, "currency": "AED", "included": "Premium IVF cycle, medications", "notes": "Luxury facilities", "confidence": "High", "source": "Clinic sites", "caveats": "High success rates"},
            "Tokyo": {"low": 6000, "high": 11000, "mid": 8500, "currency": "JPY", "included": "IVF cycle, advanced care", "notes": "High standards", "confidence": "High", "source": "Clinics", "caveats": "Conservative approach"},
            "Barcelona": {"low": 5500, "high": 10000, "mid": 7750, "currency": "EUR", "included": "IVF cycle, medications", "notes": "EU standards", "confidence": "Medium", "source": "Clinics", "caveats": "EU pricing"},
            "London": {"low": 7000, "high": 13000, "mid": 10000, "currency": "GBP", "included": "IVF cycle, premium care", "notes": "Top facilities", "confidence": "High", "source": "Clinics", "caveats": "Very expensive"},
            "Paris": {"low": 6500, "high": 12000, "mid": 9250, "currency": "EUR", "included": "IVF cycle, medications", "notes": "Premium EU", "confidence": "High", "source": "Clinics", "caveats": "High costs"},
            "Los Angeles": {"low": 12000, "high": 20000, "mid": 16000, "currency": "USD", "included": "IVF cycle, premium medications", "notes": "Top specialists", "confidence": "High", "source": "US clinics", "caveats": "Very expensive"},
            "New York City": {"low": 13000, "high": 22000, "mid": 17500, "currency": "USD", "included": "IVF cycle, comprehensive care", "notes": "Best facilities", "confidence": "High", "source": "US clinics", "caveats": "Highest US costs"},
        }
    },
    {
        "procedure": "Bariatric Surgery (Gastric Sleeve)",
        "category": "Weight Loss",
        "pricing": {
            "Bangkok": {"low": 8000, "high": 12000, "mid": 10000, "currency": "THB", "included": "Surgery, hospital stay, follow-up", "notes": "Pre-op tests", "confidence": "High", "source": "Clinic sites", "caveats": "High quality care"},
            "Seoul": {"low": 9000, "high": 14000, "mid": 11500, "currency": "KRW", "included": "Surgery, advanced techniques", "notes": "Post-op program", "confidence": "High", "source": "Clinics", "caveats": "Premium care"},
            "Istanbul": {"low": 3500, "high": 5500, "mid": 4500, "currency": "TRY", "included": "All-inclusive package", "notes": "Hotel, transfers, tests", "confidence": "High", "source": "Aggregators", "caveats": "Very competitive"},
            "Ho Chi Minh City": {"low": 7000, "high": 11000, "mid": 9000, "currency": "VND", "included": "Surgery, hospital stay", "notes": "Basic follow-up", "confidence": "Medium", "source": "Local clinics", "caveats": "Growing expertise"},
            "Kuala Lumpur": {"low": 7500, "high": 11500, "mid": 9500, "currency": "MYR", "included": "Surgery, hospital, follow-up", "notes": "Nutritionist support", "confidence": "Medium", "source": "Clinic sites", "caveats": "Mid-range quality"},
            "Delhi": {"low": 4500, "high": 7000, "mid": 5750, "currency": "INR", "included": "Surgery, hospital stay", "notes": "Basic care", "confidence": "Medium", "source": "Aggregators", "caveats": "Affordable option"},
            "Mumbai": {"low": 5000, "high": 7500, "mid": 6250, "currency": "INR", "included": "Surgery, hospital, tests", "notes": "Follow-up care", "confidence": "Medium", "source": "Clinics", "caveats": "Good value"},
            "Mexico City": {"low": 5000, "high": 7000, "mid": 6000, "currency": "MXN", "included": "All-inclusive package", "notes": "Hotel, transfers", "confidence": "High", "source": "Clinic sites", "caveats": "Popular destination"},
            "Medellín": {"low": 5500, "high": 7500, "mid": 6500, "currency": "COP", "included": "Surgery, hospital stay", "notes": "Follow-up program", "confidence": "Medium", "source": "Aggregators", "caveats": "Medical tourism hub"},
            "Bogotá": {"low": 5700, "high": 7700, "mid": 6700, "currency": "COP", "included": "Surgery, hospital, tests", "notes": "Post-op care", "confidence": "Medium", "source": "Clinics", "caveats": "Similar to Medellín"},
            "Prague": {"low": 7000, "high": 11000, "mid": 9000, "currency": "CZK", "included": "Surgery, hospital, follow-up", "notes": "EU standards", "confidence": "Medium", "source": "Clinic sites", "caveats": "EU pricing"},
            "Budapest": {"low": 6500, "high": 10500, "mid": 8500, "currency": "HUF", "included": "Surgery, comprehensive care", "notes": "All-inclusive", "confidence": "Medium", "source": "Aggregators", "caveats": "Value EU"},
            "Warsaw": {"low": 6800, "high": 10800, "mid": 8800, "currency": "PLN", "included": "Surgery, hospital stay", "notes": "Follow-up visits", "confidence": "Medium", "source": "Clinics", "caveats": "Growing market"},
            "Dubai": {"low": 9000, "high": 14000, "mid": 11500, "currency": "AED", "included": "Premium surgery, luxury hospital", "notes": "VIP care", "confidence": "High", "source": "Clinic sites", "caveats": "Luxury pricing"},
            "Tokyo": {"low": 10000, "high": 15000, "mid": 12500, "currency": "JPY", "included": "Surgery, advanced care", "notes": "High standards", "confidence": "High", "source": "Clinics", "caveats": "Premium quality"},
            "Barcelona": {"low": 8000, "high": 12000, "mid": 10000, "currency": "EUR", "included": "Surgery, hospital, follow-up", "notes": "EU standards", "confidence": "Medium", "source": "Clinics", "caveats": "EU pricing"},
            "London": {"low": 10000, "high": 16000, "mid": 13000, "currency": "GBP", "included": "Surgery, private hospital", "notes": "Premium care", "confidence": "High", "source": "Clinics", "caveats": "Very expensive"},
            "Paris": {"low": 9500, "high": 15000, "mid": 12250, "currency": "EUR", "included": "Surgery, hospital, care", "notes": "Premium EU", "confidence": "High", "source": "Clinics", "caveats": "High costs"},
            "Los Angeles": {"low": 15000, "high": 25000, "mid": 20000, "currency": "USD", "included": "Surgery, comprehensive program", "notes": "Top surgeons", "confidence": "High", "source": "US clinics", "caveats": "Very expensive"},
            "New York City": {"low": 16000, "high": 27000, "mid": 21500, "currency": "USD", "included": "Surgery, premium care", "notes": "Best facilities", "confidence": "High", "source": "US clinics", "caveats": "Highest US costs"},
        }
    },
    {
        "procedure": "Knee Replacement",
        "category": "Orthopedic",
        "pricing": {
            "Bangkok": {"low": 10000, "high": 15000, "mid": 12500, "currency": "THB", "included": "Surgery, implant, hospital stay", "notes": "Rehab program", "confidence": "High", "source": "Clinic sites", "caveats": "International hospitals"},
            "Seoul": {"low": 12000, "high": 18000, "mid": 15000, "currency": "KRW", "included": "Surgery, premium implant", "notes": "Advanced techniques", "confidence": "High", "source": "Clinics", "caveats": "High-tech care"},
            "Istanbul": {"low": 8000, "high": 12000, "mid": 10000, "currency": "TRY", "included": "All-inclusive package", "notes": "Hotel, transfers, rehab", "confidence": "High", "source": "Aggregators", "caveats": "JCI-accredited"},
            "Ho Chi Minh City": {"low": 9000, "high": 13000, "mid": 11000, "currency": "VND", "included": "Surgery, implant, hospital", "notes": "Basic rehab", "confidence": "Medium", "source": "Local clinics", "caveats": "Variable quality"},
            "Kuala Lumpur": {"low": 9500, "high": 13500, "mid": 11500, "currency": "MYR", "included": "Surgery, implant, stay", "notes": "Physio program", "confidence": "Medium", "source": "Clinic sites", "caveats": "Mid-range quality"},
            "Delhi": {"low": 3500, "high": 6000, "mid": 4750, "currency": "INR", "included": "Surgery, implant, hospital", "notes": "Basic rehab", "confidence": "High", "source": "Aggregators", "caveats": "Very affordable"},
            "Mumbai": {"low": 4000, "high": 6500, "mid": 5250, "currency": "INR", "included": "Surgery, implant, care", "notes": "Rehab program", "confidence": "High", "source": "Clinics", "caveats": "Excellent value"},
            "Mexico City": {"low": 9000, "high": 13000, "mid": 11000, "currency": "MXN", "included": "Surgery, implant, hospital", "notes": "Rehab included", "confidence": "High", "source": "Clinic sites", "caveats": "Quality care"},
            "Medellín": {"low": 8500, "high": 12500, "mid": 10500, "currency": "COP", "included": "Surgery, implant, stay", "notes": "Physio support", "confidence": "Medium", "source": "Aggregators", "caveats": "Good facilities"},
            "Bogotá": {"low": 8700, "high": 12700, "mid": 10700, "currency": "COP", "included": "Surgery, implant, hospital", "notes": "Rehab program", "confidence": "Medium", "source": "Clinics", "caveats": "Similar to Medellín"},
            "Prague": {"low": 10000, "high": 14000, "mid": 12000, "currency": "CZK", "included": "Surgery, implant, care", "notes": "EU standards", "confidence": "Medium", "source": "Clinic sites", "caveats": "EU pricing"},
            "Budapest": {"low": 9500, "high": 13500, "mid": 11500, "currency": "HUF", "included": "Surgery, implant, rehab", "notes": "Comprehensive care", "confidence": "Medium", "source": "Aggregators", "caveats": "Value EU"},
            "Warsaw": {"low": 9800, "high": 13800, "mid": 11800, "currency": "PLN", "included": "Surgery, implant, hospital", "notes": "Physio program", "confidence": "Medium", "source": "Clinics", "caveats": "Growing expertise"},
            "Dubai": {"low": 13000, "high": 19000, "mid": 16000, "currency": "AED", "included": "Premium surgery, luxury hospital", "notes": "VIP rehab", "confidence": "High", "source": "Clinic sites", "caveats": "Luxury care"},
            "Tokyo": {"low": 14000, "high": 20000, "mid": 17000, "currency": "JPY", "included": "Surgery, premium implant", "notes": "Advanced rehab", "confidence": "High", "source": "Clinics", "caveats": "Premium quality"},
            "Barcelona": {"low": 11000, "high": 16000, "mid": 13500, "currency": "EUR", "included": "Surgery, implant, care", "notes": "EU standards", "confidence": "Medium", "source": "Clinics", "caveats": "EU pricing"},
            "London": {"low": 15000, "high": 22000, "mid": 18500, "currency": "GBP", "included": "Surgery, private hospital", "notes": "Premium care", "confidence": "High", "source": "Clinics", "caveats": "Very expensive"},
            "Paris": {"low": 14000, "high": 21000, "mid": 17500, "currency": "EUR", "included": "Surgery, implant, rehab", "notes": "Premium EU", "confidence": "High", "source": "Clinics", "caveats": "High costs"},
            "Los Angeles": {"low": 25000, "high": 40000, "mid": 32500, "currency": "USD", "included": "Surgery, premium implant", "notes": "Top surgeons", "confidence": "High", "source": "US clinics", "caveats": "Very expensive"},
            "New York City": {"low": 27000, "high": 45000, "mid": 36000, "currency": "USD", "included": "Surgery, comprehensive care", "notes": "Best facilities", "confidence": "High", "source": "US clinics", "caveats": "Highest US costs"},
        }
    },
    {
        "procedure": "Hip Replacement",
        "category": "Orthopedic",
        "pricing": {
            "Bangkok": {"low": 11000, "high": 16000, "mid": 13500, "currency": "THB", "included": "Surgery, implant, hospital stay", "notes": "Rehab program", "confidence": "High", "source": "Clinic sites", "caveats": "International hospitals"},
            "Seoul": {"low": 13000, "high": 19000, "mid": 16000, "currency": "KRW", "included": "Surgery, premium implant", "notes": "Advanced techniques", "confidence": "High", "source": "Clinics", "caveats": "High-tech care"},
            "Istanbul": {"low": 8500, "high": 13000, "mid": 10750, "currency": "TRY", "included": "All-inclusive package", "notes": "Hotel, transfers, rehab", "confidence": "High", "source": "Aggregators", "caveats": "JCI-accredited"},
            "Ho Chi Minh City": {"low": 9500, "high": 14000, "mid": 11750, "currency": "VND", "included": "Surgery, implant, hospital", "notes": "Basic rehab", "confidence": "Medium", "source": "Local clinics", "caveats": "Variable quality"},
            "Kuala Lumpur": {"low": 10000, "high": 14500, "mid": 12250, "currency": "MYR", "included": "Surgery, implant, stay", "notes": "Physio program", "confidence": "Medium", "source": "Clinic sites", "caveats": "Mid-range quality"},
            "Delhi": {"low": 4000, "high": 7000, "mid": 5500, "currency": "INR", "included": "Surgery, implant, hospital", "notes": "Basic rehab", "confidence": "High", "source": "Aggregators", "caveats": "Very affordable"},
            "Mumbai": {"low": 4500, "high": 7500, "mid": 6000, "currency": "INR", "included": "Surgery, implant, care", "notes": "Rehab program", "confidence": "High", "source": "Clinics", "caveats": "Excellent value"},
            "Mexico City": {"low": 9500, "high": 14000, "mid": 11750, "currency": "MXN", "included": "Surgery, implant, hospital", "notes": "Rehab included", "confidence": "High", "source": "Clinic sites", "caveats": "Quality care"},
            "Medellín": {"low": 9000, "high": 13500, "mid": 11250, "currency": "COP", "included": "Surgery, implant, stay", "notes": "Physio support", "confidence": "Medium", "source": "Aggregators", "caveats": "Good facilities"},
            "Bogotá": {"low": 9200, "high": 13700, "mid": 11450, "currency": "COP", "included": "Surgery, implant, hospital", "notes": "Rehab program", "confidence": "Medium", "source": "Clinics", "caveats": "Similar to Medellín"},
            "Prague": {"low": 10500, "high": 15000, "mid": 12750, "currency": "CZK", "included": "Surgery, implant, care", "notes": "EU standards", "confidence": "Medium", "source": "Clinic sites", "caveats": "EU pricing"},
            "Budapest": {"low": 10000, "high": 14500, "mid": 12250, "currency": "HUF", "included": "Surgery, implant, rehab", "notes": "Comprehensive care", "confidence": "Medium", "source": "Aggregators", "caveats": "Value EU"},
            "Warsaw": {"low": 10300, "high": 14800, "mid": 12550, "currency": "PLN", "included": "Surgery, implant, hospital", "notes": "Physio program", "confidence": "Medium", "source": "Clinics", "caveats": "Growing expertise"},
            "Dubai": {"low": 14000, "high": 20000, "mid": 17000, "currency": "AED", "included": "Premium surgery, luxury hospital", "notes": "VIP rehab", "confidence": "High", "source": "Clinic sites", "caveats": "Luxury care"},
            "Tokyo": {"low": 15000, "high": 21000, "mid": 18000, "currency": "JPY", "included": "Surgery, premium implant", "notes": "Advanced rehab", "confidence": "High", "source": "Clinics", "caveats": "Premium quality"},
            "Barcelona": {"low": 11500, "high": 17000, "mid": 14250, "currency": "EUR", "included": "Surgery, implant, care", "notes": "EU standards", "confidence": "Medium", "source": "Clinics", "caveats": "EU pricing"},
            "London": {"low": 16000, "high": 23000, "mid": 19500, "currency": "GBP", "included": "Surgery, private hospital", "notes": "Premium care", "confidence": "High", "source": "Clinics", "caveats": "Very expensive"},
            "Paris": {"low": 15000, "high": 22000, "mid": 18500, "currency": "EUR", "included": "Surgery, implant, rehab", "notes": "Premium EU", "confidence": "High", "source": "Clinics", "caveats": "High costs"},
            "Los Angeles": {"low": 27000, "high": 42000, "mid": 34500, "currency": "USD", "included": "Surgery, premium implant", "notes": "Top surgeons", "confidence": "High", "source": "US clinics", "caveats": "Very expensive"},
            "New York City": {"low": 29000, "high": 47000, "mid": 38000, "currency": "USD", "included": "Surgery, comprehensive care", "notes": "Best facilities", "confidence": "High", "source": "US clinics", "caveats": "Highest US costs"},
        }
    },
    {
        "procedure": "Gastric Bypass",
        "category": "Weight Loss",
        "pricing": {
            "Bangkok": {"low": 9000, "high": 13000, "mid": 11000, "currency": "THB", "included": "Surgery, hospital stay, follow-up", "notes": "Pre-op tests", "confidence": "High", "source": "Clinic sites", "caveats": "High quality care"},
            "Seoul": {"low": 10000, "high": 15000, "mid": 12500, "currency": "KRW", "included": "Surgery, advanced techniques", "notes": "Post-op program", "confidence": "High", "source": "Clinics", "caveats": "Premium care"},
            "Istanbul": {"low": 4000, "high": 6500, "mid": 5250, "currency": "TRY", "included": "All-inclusive package", "notes": "Hotel, transfers, tests", "confidence": "High", "source": "Aggregators", "caveats": "Very competitive"},
            "Ho Chi Minh City": {"low": 8000, "high": 12000, "mid": 10000, "currency": "VND", "included": "Surgery, hospital stay", "notes": "Basic follow-up", "confidence": "Medium", "source": "Local clinics", "caveats": "Growing expertise"},
            "Kuala Lumpur": {"low": 8500, "high": 12500, "mid": 10500, "currency": "MYR", "included": "Surgery, hospital, follow-up", "notes": "Nutritionist support", "confidence": "Medium", "source": "Clinic sites", "caveats": "Mid-range quality"},
            "Delhi": {"low": 5000, "high": 8000, "mid": 6500, "currency": "INR", "included": "Surgery, hospital stay", "notes": "Basic care", "confidence": "Medium", "source": "Aggregators", "caveats": "Affordable option"},
            "Mumbai": {"low": 5500, "high": 8500, "mid": 7000, "currency": "INR", "included": "Surgery, hospital, tests", "notes": "Follow-up care", "confidence": "Medium", "source": "Clinics", "caveats": "Good value"},
            "Mexico City": {"low": 5500, "high": 8500, "mid": 7000, "currency": "MXN", "included": "All-inclusive package", "notes": "Hotel, transfers", "confidence": "High", "source": "Clinic sites", "caveats": "Popular destination"},
            "Medellín": {"low": 6000, "high": 8500, "mid": 7250, "currency": "COP", "included": "Surgery, hospital stay", "notes": "Follow-up program", "confidence": "Medium", "source": "Aggregators", "caveats": "Medical tourism hub"},
            "Bogotá": {"low": 6200, "high": 8700, "mid": 7450, "currency": "COP", "included": "Surgery, hospital, tests", "notes": "Post-op care", "confidence": "Medium", "source": "Clinics", "caveats": "Similar to Medellín"},
            "Prague": {"low": 8000, "high": 12000, "mid": 10000, "currency": "CZK", "included": "Surgery, hospital, follow-up", "notes": "EU standards", "confidence": "Medium", "source": "Clinic sites", "caveats": "EU pricing"},
            "Budapest": {"low": 7500, "high": 11500, "mid": 9500, "currency": "HUF", "included": "Surgery, comprehensive care", "notes": "All-inclusive", "confidence": "Medium", "source": "Aggregators", "caveats": "Value EU"},
            "Warsaw": {"low": 7800, "high": 11800, "mid": 9800, "currency": "PLN", "included": "Surgery, hospital stay", "notes": "Follow-up visits", "confidence": "Medium", "source": "Clinics", "caveats": "Growing market"},
            "Dubai": {"low": 10000, "high": 15000, "mid": 12500, "currency": "AED", "included": "Premium surgery, luxury hospital", "notes": "VIP care", "confidence": "High", "source": "Clinic sites", "caveats": "Luxury pricing"},
            "Tokyo": {"low": 11000, "high": 16000, "mid": 13500, "currency": "JPY", "included": "Surgery, advanced care", "notes": "High standards", "confidence": "High", "source": "Clinics", "caveats": "Premium quality"},
            "Barcelona": {"low": 9000, "high": 13000, "mid": 11000, "currency": "EUR", "included": "Surgery, hospital, follow-up", "notes": "EU standards", "confidence": "Medium", "source": "Clinics", "caveats": "EU pricing"},
            "London": {"low": 11000, "high": 17000, "mid": 14000, "currency": "GBP", "included": "Surgery, private hospital", "notes": "Premium care", "confidence": "High", "source": "Clinics", "caveats": "Very expensive"},
            "Paris": {"low": 10500, "high": 16000, "mid": 13250, "currency": "EUR", "included": "Surgery, hospital, care", "notes": "Premium EU", "confidence": "High", "source": "Clinics", "caveats": "High costs"},
            "Los Angeles": {"low": 16000, "high": 27000, "mid": 21500, "currency": "USD", "included": "Surgery, comprehensive program", "notes": "Top surgeons", "confidence": "High", "source": "US clinics", "caveats": "Very expensive"},
            "New York City": {"low": 17000, "high": 29000, "mid": 23000, "currency": "USD", "included": "Surgery, premium care", "notes": "Best facilities", "confidence": "High", "source": "US clinics", "caveats": "Highest US costs"},
        }
    },
    {
        "procedure": "Dental Veneers (Full Mouth)",
        "category": "Dental",
        "pricing": {
            "Bangkok": {"low": 6000, "high": 10000, "mid": 8000, "currency": "THB", "included": "16-20 veneers, consultation", "notes": "Porcelain veneers", "confidence": "High", "source": "Clinic sites", "caveats": "Major dental hub"},
            "Seoul": {"low": 7000, "high": 12000, "mid": 9500, "currency": "KRW", "included": "Veneers, advanced design", "notes": "Digital smile design", "confidence": "High", "source": "Clinics", "caveats": "Premium materials"},
            "Istanbul": {"low": 4000, "high": 7000, "mid": 5500, "currency": "TRY", "included": "Full mouth veneers, hotel", "notes": "All-inclusive package", "confidence": "High", "source": "Aggregators", "caveats": "Very competitive"},
            "Ho Chi Minh City": {"low": 5000, "high": 8500, "mid": 6750, "currency": "VND", "included": "Veneers, consultation", "notes": "Porcelain veneers", "confidence": "Medium", "source": "Local clinics", "caveats": "Large variance"},
            "Kuala Lumpur": {"low": 5500, "high": 9000, "mid": 7250, "currency": "MYR", "included": "Full mouth veneers", "notes": "Quality materials", "confidence": "Medium", "source": "Clinic sites", "caveats": "Mid-range quality"},
            "Delhi": {"low": 3500, "high": 6000, "mid": 4750, "currency": "INR", "included": "Veneers, consultation", "notes": "Basic porcelain", "confidence": "Medium", "source": "Aggregators", "caveats": "Cost leader"},
            "Mumbai": {"low": 4000, "high": 6500, "mid": 5250, "currency": "INR", "included": "Full mouth veneers", "notes": "Quality veneers", "confidence": "Medium", "source": "Clinics", "caveats": "Good value"},
            "Mexico City": {"low": 5000, "high": 8500, "mid": 6750, "currency": "MXN", "included": "Veneers, consultation", "notes": "Premium porcelain", "confidence": "High", "source": "Clinic sites", "caveats": "Popular with US"},
            "Medellín": {"low": 4500, "high": 7500, "mid": 6000, "currency": "COP", "included": "Full mouth veneers", "notes": "Quality materials", "confidence": "Medium", "source": "Aggregators", "caveats": "Dental tourism hub"},
            "Bogotá": {"low": 4700, "high": 7700, "mid": 6200, "currency": "COP", "included": "Veneers, consultation", "notes": "Porcelain veneers", "confidence": "Medium", "source": "Clinics", "caveats": "Similar pricing"},
            "Prague": {"low": 6000, "high": 10000, "mid": 8000, "currency": "CZK", "included": "Full mouth veneers", "notes": "EU standards", "confidence": "Medium", "source": "Clinic sites", "caveats": "EU pricing"},
            "Budapest": {"low": 5500, "high": 9500, "mid": 7500, "currency": "HUF", "included": "Veneers, consultation", "notes": "Quality materials", "confidence": "Medium", "source": "Aggregators", "caveats": "Value EU"},
            "Warsaw": {"low": 5800, "high": 9800, "mid": 7800, "currency": "PLN", "included": "Full mouth veneers", "notes": "Premium veneers", "confidence": "Medium", "source": "Clinics", "caveats": "Growing market"},
            "Dubai": {"low": 8000, "high": 14000, "mid": 11000, "currency": "AED", "included": "Premium veneers, luxury clinic", "notes": "Top materials", "confidence": "High", "source": "Clinic sites", "caveats": "Luxury pricing"},
            "Tokyo": {"low": 9000, "high": 15000, "mid": 12000, "currency": "JPY", "included": "Full mouth veneers", "notes": "High quality", "confidence": "High", "source": "Clinics", "caveats": "Premium quality"},
            "Barcelona": {"low": 7000, "high": 12000, "mid": 9500, "currency": "EUR", "included": "Veneers, consultation", "notes": "EU standards", "confidence": "Medium", "source": "Clinics", "caveats": "EU pricing"},
            "London": {"low": 10000, "high": 18000, "mid": 14000, "currency": "GBP", "included": "Premium veneers, private clinic", "notes": "Top quality", "confidence": "High", "source": "Clinics", "caveats": "Very expensive"},
            "Paris": {"low": 9500, "high": 17000, "mid": 13250, "currency": "EUR", "included": "Full mouth veneers", "notes": "Premium EU", "confidence": "High", "source": "Clinics", "caveats": "High costs"},
            "Los Angeles": {"low": 15000, "high": 30000, "mid": 22500, "currency": "USD", "included": "Premium veneers", "notes": "Celebrity dentists", "confidence": "High", "source": "US clinics", "caveats": "Very expensive"},
            "New York City": {"low": 16000, "high": 35000, "mid": 25500, "currency": "USD", "included": "Full mouth reconstruction", "notes": "Top dentists", "confidence": "High", "source": "US clinics", "caveats": "Highest US costs"},
        }
    },
]

# Convert to flat array format
for procedure_data in new_procedures:
    procedure_name = procedure_data["procedure"]
    category = procedure_data["category"]

    for city_name, city_info in cities_data.items():
        if city_name in procedure_data["pricing"]:
            pricing = procedure_data["pricing"][city_name]

            data.append({
                "procedure": procedure_name,
                "category": category,
                "city": city_name,
                "country": city_info["country"],
                "region": city_info["region"],
                "price_low_usd": pricing["low"],
                "price_high_usd": pricing["high"],
                "price_mid_usd": pricing["mid"],
                "currency": pricing["currency"],
                "included": pricing["included"],
                "notes": pricing["notes"],
                "confidence": pricing["confidence"],
                "source": pricing["source"],
                "caveats": pricing["caveats"],
                "lat": city_info["lat"],
                "lng": city_info["lng"]
            })

# Write updated data
with open('data.json', 'w') as f:
    json.dump(data, f, indent=2)

print(f"Successfully added {len(new_procedures)} new procedures")
print(f"Total records now: {len(data)}")
